FROM maven:3.6.3-openjdk-14

ARG TAG
ARG BROWSER
ARG URL
ARG SUITE
ARG EDITION
ARG TEST_TAG
ARG THREADS

WORKDIR /

COPY ./ /usr/src/app/.
WORKDIR /usr/src/app
RUN mvn compile

CMD /usr/bin/mvn clean test -Dcucumber.filter.tags="${TEST_TAG}" -Dtag=${TAG} -Dbrowser=${BROWSER} -Dsuite=${SUITE} -Durl=${URL} -Dedition=${EDITION} -Dthreads.count=${THREADS} -Drun=cloud