FROM maven:3.6.3-openjdk-14

ARG SUITE
ARG TEST_TAG

WORKDIR /

COPY ./ /usr/src/app/.
WORKDIR /usr/src/app
RUN mvn compile

CMD /usr/bin/mvn clean test -Dcucumber.filter.tags="${TEST_TAG}" -Dsuite=${SUITE} -Drun=cloud